### PR TITLE
Set a global variable containing the dragged row to be used by other …

### PR DESCRIPTION
**Pull request by NishalMaharaj**
…components other than the UI grid.

### CODE REVIEW

**Comment by skrajewski** [comment]
Hello @NishalMaharaj,

What is a purpose of this change? Why don't you want to use one of the available events?

Kind Regards,
Szymon

**Comment by NishalMaharaj** [comment]
Hi @Szymon,
I have a form that is used to capture data which is displayed in a grid. The grid rows can be dragged onto the form and the form fields are auto populated. I'm not sure if there is any other way to get the row entity in the form's ondrop event.

**Comment by skrajewski** [comment]
Oh, I got it. I can't merge your Pull Request because it looks to a special case. Instead of doing side effects within plugin itself, I recommend using one of the events, e.g.

```javascript
$scope.gridData.onRegisterApi = function (gridApi) {
    gridApi.draggableRows.on.rowDragged($scope, function (info, rowElement) {
        $window.draggedRow = info.targetRowEntity;
    });
};
```

It's should give the same effect.

Kind Regards,
Szymon

**Comment by NishalMaharaj** [comment]
thanks Szymon

**Pull request closed without merging**
